### ISSUE TITLE
Extension Errors

### ISSUE THREAD

**Issue by Teicu** [mystech7/Burp-Hunter#1]
Hello,  
Can you help me please fix this error. I'm using Burp Suite v1.7.22  and  Java (build 1.8.0_131-b11)
I installed the extension and I can't see any Burp Hunter tab where to add the domain and the correlation key. 

Also I got this error

> java.lang.NullPointerException
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:165)
	at burp.vj.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

>  

Thank you very much

**Comment by mystech7** [comment]
The NullPointer is because the tab didn't initialize. What version of Java are you running. I think there may be some swing component I used that requires 1.8.

**Comment by mystech7** [comment]
Using the same version of Burp and Java I'm unable to reproduce. The NullPointer there is when it tries to read the value of the configuration and expected since your Tab failed to render. I don't think there's anything OS specific in the swing panel for the tab, but what OS are you using?

*Edit*
I may have found the problem. Because Burp does not yet support saving state for plugins I'm writing a text file in the current directory. If you do not have write privileges in that directory it fails and configuration crash and burns.

**Comment by Teicu** [comment]
windows 7

btw, just tested and works fine on mac

Regards

2017-05-22 21:55 GMT+03:00 mystech7 <notifications@github.com>:

**Comment by mystech7** [comment]
I added an additional check, let me know if that changes things for you.
