### ISSUE TITLE
Missing XSS Hunter tab

### ISSUE THREAD

**Issue by ehsandeep** [mystech7/Burp-Hunter#2]
after loading the jar file, i can see the message:

Burp: 1.7.23

````
Burp Hunter by Jason Calvert
================================
This extension will perform injections for all "in scope" HTTP request made through Burp and will record the request at the specified XSS Hunter domain.
Use your own XSS Hunter domain or create one at https://xsshunter.com/
`````
but i don't see any new tab named *XSS Hunter*, so where i can add my domain or key ?

**Comment by mystech7** [comment]
Is there anything printed on the extension's error tab?

**Comment by ehsandeep** [comment]
No, nothing!

**Comment by mystech7** [comment]
Generally this occurs when Burp is ran from a directory you don't have permission to write. Burp extender does not yet support saving state so I'm writing a txt file to current directory.

If you run burp from command line do you see any errors when loading the extension?

**Comment by ehsandeep** [comment]
i am using Burp Windows installer version, they should have write permission for sure!

**Comment by mystech7** [comment]
Actually, window installer means it will not have access to write as it runs the jar from the corresponding "Program Files" directory and you can only write files there if you run Burp as admin. I'll have to think of another place in user home path for windows. Using the jar instead of the installer package should work for now.

**Comment by mystech7** [comment]
Updated config location for windows.

**Comment by ehsandeep** [comment]
Working now :+1:
